# Add this to your configuration.yaml file
input_boolean:
  lock_code_slot_1_state:
    name: Lock Code Slot 1 State
    icon: mdi:lock-check
  lock_code_slot_1_notify:
    name: Lock Code Slot 1 Notify
    icon: mdi:alarm-bell 
  lock_code_slot_2_state:
    name: Lock Code Slot 2 State
    icon: mdi:lock-check
  lock_code_slot_2_notify:
    name: Lock Code Slot 2 Notify
    icon: mdi:alarm-bell
  lock_code_slot_3_state:
    name: Lock Code Slot 3 State
    icon: mdi:lock-check
  lock_code_slot_3_notify:
    name: Lock Code Slot 3 Notify
    icon: mdi:alarm-bell
  lock_code_slot_4_state:
    name: Lock Code Slot 4 State
    icon: mdi:lock-check
  lock_code_slot_4_notify:
    name: Lock Code Slot 4 Notify
    icon: mdi:alarm-bell 
  lock_code_slot_5_state:
    name: Lock Code Slot 5 State
    icon: mdi:lock-check
  lock_code_slot_5_notify:
    name: Lock Code Slot 5 Notify
    icon: mdi:alarm-bell
  lock_code_slot_6_state:
    name: Lock Code Slot 6 State
    icon: mdi:lock-check
  lock_code_slot_6_notify:
    name: Lock Code Slot 6 Notify
    icon: mdi:alarm-bell
  lock_code_slot_7_state:
    name: Lock Code Slot 7 State
    icon: mdi:lock-check
  lock_code_slot_7_notify:
    name: Lock Code Slot 7 Notify
    icon: mdi:alarm-bell
  lock_code_slot_8_state:
    name: Lock Code Slot 8 State
    icon: mdi:lock-check
  lock_code_slot_8_notify:
    name: Lock Code Slot 8 Notify
    icon: mdi:alarm-bell
  lock_code_slot_9_state:
    name: Lock Code Slot 9 State
    icon: mdi:lock-check    
  lock_code_slot_9_notify:
    name: Lock Code Slot 9 Notify
    icon: mdi:alarm-bell
    
input_text:
  lock_code_slot_1_pin:
    name: Lock Code Slot 1 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_1_name:
    name: Lock Code Slot 1 Name
    icon: mdi:account
  lock_code_slot_2_pin:
    name: Lock Code Slot 2 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_2_name:
    name: Lock Code Slot 2 Name
    icon: mdi:account
  lock_code_slot_3_pin:
    name: Lock Code Slot 3 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_3_name:
    name: Lock Code Slot 3 Name
    icon: mdi:account
  lock_code_slot_4_pin:
    name: Lock Code Slot 4 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_4_name:
    name: Lock Code Slot 4 Name
    icon: mdi:account
  lock_code_slot_5_pin:
    name: Lock Code Slot 5 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_5_name:
    name: Lock Code Slot 5 Name
    icon: mdi:account
  lock_code_slot_6_pin:
    name: Lock Code Slot 6 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_6_name:
    name: Lock Code Slot 6 Name
    icon: mdi:account
  lock_code_slot_7_pin:
    name: Lock Code Slot 7 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_7_name:
    name: Lock Code Slot 7 Name
    icon: mdi:account
  lock_code_slot_8_pin:
    name: Lock Code Slot 8 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_8_name:
    name: Lock Code Slot 8 Name
    icon: mdi:account
  lock_code_slot_9_pin:
    name: Lock Code Slot 8 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_9_name:
    name: Lock Code Slot 8 Name
    icon: mdi:account    
