# create a new automation, edit in YAML, paste this code and modify the notify service
alias: .lock notify
description: notify when certain codes are used to unlock the doors, if notify is enabled
triggers:
  - event_type: zwave_js_notification
    event_data:
      command_class: 113
      command_class_name: Notification
      label: Access Control
      type: 6
      event: 6
      event_label: Keypad unlock operation
    trigger: event
conditions: []
actions:
  - variables:
      user_code: "{{ trigger.event.data.parameters.userId }}"
      user_name: >-
        {{ states('input_text.lock_code_slot_' ~
        trigger.event.data.parameters.userId ~ '_name') }}
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ is_state('input_boolean.lock_code_slot_' ~ user_code ~
              '_notify', 'on') }}
        sequence:
          - event: UNotify
            event_data:
              message: >-
                {{ user_name }} unlocked the door via keypad at {{
                now().strftime('%H:%M:%S') }}
              message_target: parents
              tag: doorunlocked
mode: single
