# Home Assistant Simple Lock Manager Package
# This package consolidates all YAML files into a single package file
# Place this file in your packages directory and reference it in configuration.yaml

# Input Boolean entities for lock code states and notifications
input_boolean:
  lock_code_slot_1_state:
    name: Lock Code Slot 1 State
    icon: mdi:lock-check
  lock_code_slot_1_notify:
    name: Lock Code Slot 1 Notify
    icon: mdi:alarm-bell 
  lock_code_slot_2_state:
    name: Lock Code Slot 2 State
    icon: mdi:lock-check
  lock_code_slot_2_notify:
    name: Lock Code Slot 2 Notify
    icon: mdi:alarm-bell
  lock_code_slot_3_state:
    name: Lock Code Slot 3 State
    icon: mdi:lock-check
  lock_code_slot_3_notify:
    name: Lock Code Slot 3 Notify
    icon: mdi:alarm-bell
  lock_code_slot_4_state:
    name: Lock Code Slot 4 State
    icon: mdi:lock-check
  lock_code_slot_4_notify:
    name: Lock Code Slot 4 Notify
    icon: mdi:alarm-bell 
  lock_code_slot_5_state:
    name: Lock Code Slot 5 State
    icon: mdi:lock-check
  lock_code_slot_5_notify:
    name: Lock Code Slot 5 Notify
    icon: mdi:alarm-bell
  lock_code_slot_6_state:
    name: Lock Code Slot 6 State
    icon: mdi:lock-check
  lock_code_slot_6_notify:
    name: Lock Code Slot 6 Notify
    icon: mdi:alarm-bell
  lock_code_slot_7_state:
    name: Lock Code Slot 7 State
    icon: mdi:lock-check
  lock_code_slot_7_notify:
    name: Lock Code Slot 7 Notify
    icon: mdi:alarm-bell
  lock_code_slot_8_state:
    name: Lock Code Slot 8 State
    icon: mdi:lock-check
  lock_code_slot_8_notify:
    name: Lock Code Slot 8 Notify
    icon: mdi:alarm-bell     
  lock_code_slot_9_notify:
    name: Lock Code Slot 9 Notify
    icon: mdi:alarm-bell

# Input Text entities for lock code PINs and names    
input_text:
  lock_code_slot_1_pin:
    name: Lock Code Slot 1 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_1_name:
    name: Lock Code Slot 1 Name
    icon: mdi:account
  lock_code_slot_2_pin:
    name: Lock Code Slot 2 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_2_name:
    name: Lock Code Slot 2 Name
    icon: mdi:account
  lock_code_slot_3_pin:
    name: Lock Code Slot 3 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_3_name:
    name: Lock Code Slot 3 Name
    icon: mdi:account
  lock_code_slot_4_pin:
    name: Lock Code Slot 4 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_4_name:
    name: Lock Code Slot 4 Name
    icon: mdi:account
  lock_code_slot_5_pin:
    name: Lock Code Slot 5 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_5_name:
    name: Lock Code Slot 5 Name
    icon: mdi:account
  lock_code_slot_6_pin:
    name: Lock Code Slot 6 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_6_name:
    name: Lock Code Slot 6 Name
    icon: mdi:account
  lock_code_slot_7_pin:
    name: Lock Code Slot 7 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_7_name:
    name: Lock Code Slot 7 Name
    icon: mdi:account
  lock_code_slot_8_pin:
    name: Lock Code Slot 8 PIN
    min: 5
    max: 10
    pattern: "[0-9]*"
    icon: mdi:form-textbox-password 
  lock_code_slot_8_name:
    name: Lock Code Slot 8 Name
    icon: mdi:account

# Automations for the lock manager system
automation:
  # Set Lock Codes Automation
  - alias: .locks set codes
    description: set key codes on locks (replacement for keymaster)
    trigger:
      - platform: state
        entity_id:
          - input_text.lock_code_slot_1_pin
          - input_text.lock_code_slot_2_pin
          - input_text.lock_code_slot_3_pin
          - input_text.lock_code_slot_4_pin
          - input_text.lock_code_slot_5_pin
          - input_text.lock_code_slot_6_pin
          - input_text.lock_code_slot_7_pin
          - input_text.lock_code_slot_8_pin
        for:
          hours: 0
          minutes: 0
          seconds: 5
        id: PIN
      - platform: state
        entity_id:
          - input_boolean.lock_code_slot_1_state
          - input_boolean.lock_code_slot_2_state
          - input_boolean.lock_code_slot_3_state
          - input_boolean.lock_code_slot_4_state
          - input_boolean.lock_code_slot_5_state
          - input_boolean.lock_code_slot_6_state
          - input_boolean.lock_code_slot_7_state
          - input_boolean.lock_code_slot_8_state
        id: Disable
        to: "off"
      - platform: state
        entity_id:
          - input_boolean.lock_code_slot_1_state
          - input_boolean.lock_code_slot_2_state
          - input_boolean.lock_code_slot_3_state
          - input_boolean.lock_code_slot_4_state
          - input_boolean.lock_code_slot_5_state
          - input_boolean.lock_code_slot_6_state
          - input_boolean.lock_code_slot_7_state
          - input_boolean.lock_code_slot_8_state
        id: PIN
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: PIN
              - condition: template
                value_template: >-
                  {% set mysensor = "input_boolean.lock_code_slot_" ~
                  (trigger.entity_id | replace('.','z') | list | sort | first | int)
                  ~ "_state" %}
                  {{is_state(mysensor,'on')}} 
            sequence:
              - service: zwave_js.set_lock_usercode
                data:
                  usercode: >-
                    {% set mysensor = "input_text.lock_code_slot_" ~
                    (trigger.entity_id | replace('.','z') | list | sort | first |
                    int) ~ "_PIN" %}   {{states(mysensor)}}
                  code_slot: >-
                    {{trigger.entity_id | replace('.','z') | list | sort | first |
                    int}}
                target:
                  entity_id:
                    - lock.lock_deck_north_door # change these to your lock entities
                    - lock.lock_front_door
                    - lock.garage_side_door_lock
                enabled: true
          - conditions:
              - condition: trigger
                id: Disable
            sequence:
              - service: zwave_js.clear_lock_usercode
                data:
                  code_slot: >-
                    {{trigger.entity_id | replace('.','z') | list | sort | first |
                    int}}
                target:
                  entity_id:
                    - lock.lock_deck_north_door # change these to your lock entities
                    - lock.lock_front_door
                    - lock.garage_side_door_lock
    mode: queued
    max: 10

  # Lock Code Notification Automation
  - alias: .lock notify
    description: notify when certain codes are used to unlock the doors, if notify is enabled
    triggers:
      - event_type: zwave_js_notification
        event_data:
          command_class: 113
          command_class_name: Notification
          label: Access Control
          type: 6
          event: 6
          event_label: Keypad unlock operation
        trigger: event
    conditions: []
    actions:
      - variables:
          user_code: "{{ trigger.event.data.parameters.userId }}"
          user_name: >-
            {{ states('input_text.lock_code_slot_' ~
            trigger.event.data.parameters.userId ~ '_name') }}
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ is_state('input_boolean.lock_code_slot_' ~ user_code ~
                  '_notify', 'on') }}
            sequence:
              - event: UNotify
                event_data:
                  message: >-
                    {{ user_name }} unlocked the door via keypad at {{
                    now().strftime('%H:%M:%S') }}
                  message_target: parents
                  tag: doorunlocked
    mode: single
